version: "3.1"
services:
  django:
    build: ./
    container_name: django-teacha
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/app/django
    networks:
      - django-network
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  react:
    build: ./react
    container_name: react-techa
    restart: always
    volumes:
      - ./react:/app/react
    networks:
      - django-network
    command: ["npm", "start"]

networks:
  django-network:
    driver: bridge
