# Generated by Django 4.0.2 on 2022-02-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='pfps'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='lol', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mentor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
