# Generated by Django 4.0.2 on 2022-02-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_avatar_profile_bio_profile_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mentor',
            field=models.BooleanField(null=True),
        ),
    ]
